#チャットのPrefix
chat-prefix: " §2>§a>§r "

#以下のプレースホルダーが使用可能です
# {PLAYER} → プレイヤー名
# {PLAYERUUID} → プレイヤーUUID
# {PLAYERWORLD} → プレイヤーのいるワールド
# {PREFIX} → チャットのPrefix
#ログインメッセージ
login-message: true
login-message-content: ""
login-title: true
login-title-content: ""
login-subtitle-content: ""
#ログアウトメッセージ
logout-message: true
logout-message-content: ""

#コマンドブロックのログ
admin-cmdblock-commandlog: true
#プレイヤーのコマンドログ
admin-player-commandlog: true
#コンソールのコマンドログ
admin-console-commandlog: true