#チャットのPrefix
chat-prefix: " §2>§a>§r "

#以下のプレースホルダーが使用可能です
# {PLAYER} → プレイヤー名
# {PLAYERUUID} → プレイヤーUUID
# {PLAYERWORLD} → プレイヤーのいるワールド
# {PREFIX} → チャットのPrefix
#ログインメッセージ
login-message: true
login-message-content: ""
login-title: true
login-title-content: ""
login-subtitle-content: ""
#ログアウトメッセージ
logout-message: true
logout-message-content: ""

#コマンドブロックのログ
admin-cmdblock-commandlog: true
#プレイヤーのコマンドログ
admin-player-commandlog: true
#コンソールのコマンドログ
admin-console-commandlog: true

#データベース
# sql - mysql, mariadb
# address - データベースのアドレス (IP)
# database - 使用データベース名
# port - ポート (default 3306)
# username - ユーザー名
# password - パスワード
sql: "mysql"
address: ""
database: ""
port: 3306
username: ""
password: ""